spring:
  data:
    mongodb:
      username: sa
      password: password
      additional-hosts: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
